### ISSUE TITLE
Enhance selectable to make use of Django models.Manager

### ISSUE THREAD

**Issue by gamesbook** [mlavin/django-selectable#150]
It would be really useful to allow lookups based on Models to make use of the filters that have already been defined for a model via the model manager.  

The syntax could be simple, and the functionality would work in a similar way to how filters operate now.  The advantage would be a DRY approach; in many cases, the filters are trying emulate criteria already defined and tested elsewhere.

A concrete example is shown here, based on  the model shown in  https://docs.djangoproject.com/en/1.8/topics/db/managers/#modifying-initial-manager-querysets and the example in http://django-selectable.readthedocs.org/en/latest/lookups.html#user-lookup-example

```
from mylibrary.models import Book, DahlBookManager

from selectable.base import ModelLookup
from selectable.registry import registry


class DahlBookLookup(ModelLookup):
    model = Book
    search_fields = (
        'title__icontains',
        'author__icontains'
    )
    manager = DahlBookManager
```

**Comment by mlavin** [comment]
This is already possible by overriding [`get_queryset`][0] though that is probably poorly documented if at all.

[0]: https://github.com/mlavin/django-selectable/blob/master/selectable/base.py#L133

**Comment by gamesbook** [comment]
So, something like?

```
    def get_queryset(self):
        try:
            qs = self.model.dahl_book_manager.get_queryset()
        except AttributeError:  # Django <= 1.5.
            qs = self.model.dahl_book_manager.get_query_set()
        if self.filters:
            qs = qs.filter(**self.filters)
        return qs
```

**Comment by mlavin** [comment]
I wouldn't worry at all about the default implantation if you are going to use your own manager:
```
def get_queryset(self):
    return self.model.dahl_book_manager.all()
```

**Comment by gamesbook** [comment]
Thanks!
