### ISSUE TITLE
Restrict multiple select items

### ISSUE THREAD

**Issue by X17** [mlavin/django-selectable#151]
Is there any option to restrict the count of the multiselect items number let's say not more than 3.
I check the document couldn't find it, i guess it needs to be worked in js rather than backend.

Kindly help me on this. Thanks in advance

**Comment by mlavin** [comment]
See #96 for some info on how this could be implemented by listening for the select/change events.

**Comment by mlavin** [comment]
Closing as a duplicate of #96.
