### ISSUE TITLE
Feature Request: Link to Admin Page of ForeignKey

### ISSUE THREAD

**Issue by guettli** [mlavin/django-selectable#152]
If you use the selectable widget in the django admin interface, it would be very nice to have a link to the admin page of the selected ForeignKey.

I added a screenshot. This is the way I would like to see it:

![selectable](https://cloud.githubusercontent.com/assets/414336/9033065/7f9f66ae-39c4-11e5-9ee8-310507de9cce.png)

In this example: If you click on [edit] you get to the admin page of the object "System" of model "Type".

I have not looked at the source yet.  Maybe I am missing something and this is already possible :-)

What do you think?

Would you accept a patch? 

Do you prefer to code this yourself?

**Comment by mlavin** [comment]
Yes if this could be made to work it would be accepted. Sounds similar to #145.

**Comment by guettli** [comment]
In #145 the screenshot has a pencil and "delete" icon. I don't see them in my case. I just see the "add" icon.

Where does the pencil icon come from? 

What happens if you press it?

**Comment by mlavin** [comment]
As noted in the case, those come from django-admin-enhancer which is available as an external app prior to 1.8 but landed in Django itself in 1.8. Clicking the pencil icon takes you to the edit page for the item as you were describing here.

**Comment by guettli** [comment]
If Django 1.8 brings this feature, there is no need to implement this in django-selectable.

I close my issue.

PS: We are currently in the upgrade process to Django1.7. It's quite hard since there are many apps with dependencies.

**Comment by gamesbook** [comment]
_" It's quite hard since there are many apps with dependencies."_

Welcome to the wonderful world of the open source pyramid stack - the higher you climb ...
