### ISSUE TITLE
Django 1.8 compatibility as final package

### ISSUE THREAD

**Issue by TZanke** [mlavin/django-selectable#153]
Hello, 

at the moment we are upgrading our projects to Django 1.7. 
Now we are receiving RemovedInDjango18Warning in our log files because of Django-selectable.
(the fix is actually included in master / https://github.com/mlavin/django-selectable/commit/3c8a9a53636ba7ce83c0b263d0eba279ae42a45c)

Furthermore, we plan to upgrade Django to 1.8, but there is no new Django-selectable version including the needed change.

When is a new release planned, including the fix commit?

Best regards

**Comment by mlavin** [comment]
I had a milestone for a 1.0 release and then life got in the way. But this change is only in the test suite, not in selectable itself. I would expect that 0.9.X works with Django 1.8 as is.

**Comment by mlavin** [comment]
https://pypi.python.org/pypi/django-selectable/1.0.0 supports 1.7-1.10.
