### ISSUE TITLE
Disable pagination for performance reasons

### ISSUE THREAD

**Issue by josschwa** [mlavin/django-selectable#161]
I'm using autocomplete on a postgres table with around 1 mio records. Django selectable does always do two queries: 
- the first one is a "select count(..)" which is done by django core paginator and is needed for pagination. It just uses the default count() method of the object list. 
- the second one is the actual "select" query to fetch the results to display

I've some performance issues which origin from the "select count" query. It takes up to 6 seconds in my setup and can not be sped up with db indexes.
As I don't need pagination it would be great if I could disable it in the config.

**Comment by josschwa** [comment]
Well, I could reach this by overwriting format_results() in lookups.py like that:

    def format_results(self, raw_data, options):
        results = {}
        results['data'] = [self.format_item(item) for item in raw_data[0:settings.SELECTABLE_MAX_LIMIT]]
        results['meta'] = options.copy()
        return results

I suppose you can close this ticket if you want.

**Comment by mlavin** [comment]
Glad you found a way to make this work.
