### ISSUE TITLE
support "disabled" attribute properly

### ISSUE THREAD

**Issue by srkunze** [mlavin/django-selectable#163]
First of all, I want to thank you for this fine package. :)

While testing HTML's disabled="disabled", I noticed that it's only partially disabled.

1) the background of the text input is not gray
2) the user can still click on the dropdown menu
3) the user can still remove items from the selection

I use "AutoComboboxSelectMultipleWidget".

**Comment by srkunze** [comment]
My current solution works like this:


**in Python**
```
form.fields[field_name].widget.attrs['disabled'] = 'disabled'
```

**some JS**
```
    $('input.ui-autocomplete-input[disabled] + .ui-combo-button + .ui-helper-hidden-accessible + .selectable-deck > .selectable-deck-item > .selectable-deck-remove').remove();
    $('input.ui-autocomplete-input[disabled] + .ui-combo-button').unbind();
```

**some CSS**
```
input.ui-combo-input[disabled] {
    background: rgb(235, 235, 228);
}
```

**Comment by JoshAddington** [comment]
This can be closed, correct? @mlavin

**Comment by mlavin** [comment]
:+1:
