### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by TZanke** [mlavin/django-selectable#172]
I requested the german translation for django-selectable at https://www.transifex.com/mlavin/django-selectable/ but never got accepted.

How to get involved in translations?

**Comment by mlavin** [comment]
That's odd. I accepted the request and German is listed as a language but I don't see any translators/collaborators listed for German. I've sent invites for to join the translation team.

**Comment by TZanke** [comment]
Thank you, i added German.

Germany (Germany) can by removed. It should inherit from German.

Best regards Tobias

**Comment by mlavin** [comment]
Fantastic! Thank you!

**Comment by JoshAddington** [comment]
This can be closed, correct? @TZanke
