### ISSUE TITLE
Required field with AutoCompleteSelectMultipleWidget cannot be submitted

### ISSUE THREAD

**Issue by JoshAddington** [mlavin/django-selectable#175]
I have a required field that is using the AutoCompleteSelectMultipleWidget.

Chrome and Firefox no longer allow submission of the form, as it sees that the field input is empty

![screen shot 2016-12-14 at 11 49 08 am](https://cloud.githubusercontent.com/assets/7219131/21191603/a8181ce4-c1f3-11e6-8874-b669bab7e1e5.png)

When I set the form field to required=False, the form predictably allows that field to be empty.

**Comment by JoshAddington** [comment]
Setting `novalidate` on the form disables browser validation and lets the form be submitted. Not sure if that's how you think it should be handled, @mlavin.

**Comment by mlavin** [comment]
Ugh. That's a fine work-around but we should remove the required attribute from the widget rendering.
