### ISSUE TITLE
Selecting entry with enter submits form

### ISSUE THREAD

**Issue by TZanke** [mlavin/django-selectable#178]
Hello,

is it possible to select an entry with enter, without submitting the form? At the moment our customers have to use tab. but this feels inconvenient. The selection UI does not look like if it should trigger an form submit

Best regards
Tobias

**Comment by mlavin** [comment]
The [`autoFocus` option][0] will automatically select the first item which should respond to the enter selection rather than submitting the form.

[0]: https://api.jqueryui.com/autocomplete/#option-autoFocus

**Comment by TZanke** [comment]
i enabled this option temporarily in the jquery.dj.selectable.js and it does work. But one problem remains, after typing the first letters the results show up, but the first line is not selected. If i now add a other char or remove one, the first line is selected.

On JS fiddle the jquery UI Autocomplete works correct, but in Django with Django Selectable this problem occurs.

Secound Question:
`$( "#InputID" ).autocomplete( "option", "autoFocus", true );`
does not work, because input has no autocomplete?! But in UI it works correct.

**Comment by mlavin** [comment]
The JS widget is named `djselectable` so it can be configured via `$( "#InputID" ).djselectable( "option", "autoFocus", true );` or on the server side via `data-selectable-options`: http://django-selectable.readthedocs.io/en/latest/widgets.html#widgets

**Comment by TZanke** [comment]
Yes Sorry, RTFM, have found it 1 minute ago.

**Comment by mlavin** [comment]
No worries. I remember implementing it but it still took some digging to find where is was documented.
