### ISSUE TITLE
jQuery UI 1.12:  zIndex has been removed,

### ISSUE THREAD

**Issue by m-libbrecht** [mlavin/django-selectable#183]
Had an issue with django-selectable while using jQuery UI 1.12: no popup appeared.
The console showed the error: zIndex is not a function

It seems zIndex() has been removed from jQueryUI => so got stuck in line 268 
` ul.zIndex($unput.zIndex() + 1 );`
of _suggest method ( jquery.dj.selectable.js)

I tried jQuery 1.11 instead of  jQuery UI 1.12 => resolved

**Comment by mlavin** [comment]
Released v1.2.1 on PyPi today which includes this fix.
