### ISSUE TITLE
Django 1.11 compatible release?

### ISSUE THREAD

**Issue by vkurup** [mlavin/django-selectable#201]
Hi @mlavin, wondering if you'd be able to release the master branch to PyPI when you have a chance, so I can take advantage of all the Django 1.11 compatible goodness.

Hope you're doing well!

**Comment by mlavin** [comment]
I released 1.1 back in Jan which is compatible with Django 1.11. Looks like the change log wasn't correctly updated :(

**Comment by vkurup** [comment]
I have no idea how I wrote 1.11 TWICE when I meant 2.0, specifically the work you merged in #199

**Comment by mattaw** [comment]
Well can I ask for a PyPi release that supports 2.0? (If @vkurup was asking for a PyPi 2.0 release 👍  )

**Comment by mlavin** [comment]
Yes I'll package the current master to PyPi tomorrow.

**Comment by mlavin** [comment]
v1.2.0 has been uploaded to PyPi and the test suite is passing for Django 2.0, 2.1, and the current master for 2.2. Thanks for your patience everyone.
