### ISSUE TITLE
No module named 'django.utils.six'

### ISSUE THREAD

**Issue by infosrabah** [mlavin/django-selectable#208]
Not compatible with Django 3, since six was a separate pakcage of django

fixed the issue by changing the line in base.py :

<code>from django.utils.six import string_types</code>

by this one :

<code>from six import string_types</code>

Hope to see a fix in the near future.

thank's

**Comment by cpina** [comment]
Same problem here... I'll try the solution when I have time.

**Comment by cpina** [comment]
See this branch:
https://github.com/mlavin/django-selectable/pull/209

**Comment by domdinicola** [comment]
released v1.3.0 with django 3.0 support
