### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by stefan6419846** [mlavin/django-selectable#224]
What is the current maintenance status of this project? Apparently, the last commit happened in 2020, but there are at least two pending PRs for Django 4 support which are not being merged in.

According to https://github.com/mlavin/django-selectable/commit/9c72e02c1ac6ba54b0f4d874da339ea596e5c96a, @mlavin has been searching for additional maintainers since 2017 and @domdinicola jumped on it and got collaborator some time ago, but for now, general development seems to have stalled.

**Comment by domdinicola** [comment]
I'd be available to maintain this.. but I need permission or transfer of the project

**Comment by stefan6419846** [comment]
@domdinicola You already are a collaborator here according to the markers on your comments, so you should (at least in theory) already have write access and the ability to push new tags (although probably no PyPI access).

**Comment by domdinicola** [comment]
@mlavin any chance you can give me access to pypi as well?

**Comment by domdinicola** [comment]
I modernized a little bit the code to support python3.9 and django 3.2 and 4.2

**Comment by mlavin** [comment]
@domdinicola https://pypi.org/user/dom.dinicola/ was previously a maintainer on PyPi and I've changed to a full owner.

**Comment by domdinicola** [comment]
Thanks! I just released a new version https://pypi.org/project/django-selectable/

**Comment by stefan6419846** [comment]
Could you please tag the release on GitHub as well?

**Comment by domdinicola** [comment]
sure

**Comment by stefan6419846** [comment]
Thanks for stepping in. Unfortunately, it seems like the maintenance status did not really improve, as the more recent issue #228 blocking support for recent Django versions remained unaddressed for over a year now.

**Comment by domdinicola** [comment]
@stefan6419846 can you please work on a PR, I would be happy to release a new version as soon as this is fixed

**Comment by stefan6419846** [comment]
It seems like you already managed to fix this yourself in https://github.com/mlavin/django-selectable/commit/5fc33eb9bbf07267bb8a97a0e6fb84966483ba5b Sorry for not opening a PR, at the time of writing I did not have proper time to propose a fix for this as I just stumbled upon this again recently (although the issue is indeed older).
